-- CreateTable
CREATE TABLE "Teams" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "group" STRING NOT NULL,
    "name" STRING NOT NULL,
    "flag" STRING NOT NULL,

    CONSTRAINT "Teams_pkey" PRIMARY KEY ("id")
);
